name: "op-plane-gentd"
mode: "dev"
port: 10086
version: "v0.0.1"
machine_id: 1
start_time: "2000-05-09"
clientip: "192.168.0.124"

log:
  level: "info"
  filename: "logs/client.log"
  max_size: 100
  max_age: 30
  max_backups: 7

server:
    ip: "192.168.8.84"
    port: 8080
    heartbeat: 5
    hostname: "client"
